name: tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubutu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Test
        run: go test -v ./...
